### PR TITLE
Add sstable-stats.py

### PR DESCRIPTION
**Pull request by denesb**
Dump the contents of the sstable statistics file in a human-readable
form. Supports ka, la and mc format. Serialization header is not dumped
yet.

### CODE REVIEW

**Comment by denesb** [comment]
Perhaps I should rebase on top of #3's `sstablelib`. But that PR is open for two years. :(

**Comment by pdziepak** [comment]
#3 is merged now. It would be indeed good if `sstable-stats.py` reused functions form `sstablelib.py`.

**Comment by denesb** [comment]
Ok, I will send a new version soon.

**Comment by denesb** [comment]
v2 pushed, changes:
* Rebase on top of Avi's `sstablelib`
* Add `TODO` to the not yet parsed `Serialization` section
* Tolerate undecodable strings
* Remove `--verbose` option.
* Arrange code such that it can be used both via `import` or the command line (actually only the latter because the file's name contains a dash for consistency)

**Comment by denesb** [comment]
v3 pushed, changes:
* sstable_stats.parse(): take a raw bytes as the `data` parameter, instead of `sstablelib.Stream`
* sstable_stats.parse(): don't use global `data` instance
* sstable-stats.py: move "main" code into `main()` to avoid leaking variables into the global scope (python has no block scope)

**Comment by denesb** [comment]
v4 pushed, changes:
* mv sstable-stats.py sstable-statistics.py
* parse(): use the human readable type names instead of enum values as keys in the returned dict

**Pull request merged**
